name: CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "feature/**" ]

permissions:
  contents: read

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install Node dependencies
        if: hashFiles('package-lock.json') != ''
        run: npm ci
      - name: Build frontend (Vite)
        run: npm run build --if-present

  php:
    runs-on: ubuntu-latest
    if: hashFiles('composer.json') != ''
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none
          tools: composer:v2
      - name: Install PHP dependencies
        run: composer install --no-interaction --no-progress --prefer-dist
      - name: Lint PHP (basic)
        run: |
          files=$(git ls-files '*.php')
          if [ -n "$files" ]; then
            php -l $files || true
          fi
      - name: PHPUnit (if present)
        run: |
          if [ -f vendor/bin/phpunit ]; then
            vendor/bin/phpunit --testdox
          else
            echo "phpunit not present; skipping."
          fi